In [1]:
import numpy as np

In [2]:
# check type of np array
type(np.array(["deo",3,4]))

numpy.ndarray

In [3]:
# upcasting 
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
# or
np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

In [5]:
# two dimension
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

In [8]:
# n - dimensions
np.array([2,3,4,5,6,7,8,9,10,11,23,45], ndmin=4)

array([[[[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 23, 45]]]])

In [9]:
# data types
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
# data types for more than one elements
#note - 
#i2 - 16bit
#i4 - 32bit
#i8 - 64bit

x = np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [13]:
# accessing the data from above 
x[0]

(1, 2)

In [14]:
x[0][1]

2

In [17]:
# matrix
np.mat(np.array([[1,2,3,4,5],[6,7,8,9,10]]))

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [19]:
# or
np.mat('1 2 3; 3 4 5; 5 6 7')

matrix([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [27]:
# or passing list
np.mat(np.array([[1,2,3,4],[5,6,7,8,]]))

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [30]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [31]:
# Array.asarray - convert the input(list, tupple ect) to an array
a = [1,2]
type(a)

list

In [35]:
np.asarray(a)

array([1, 2])

In [36]:
type(np.asarray(a))

numpy.ndarray

In [37]:
# convert int to float on array
np.asarray(a, dtype=np.float64)

array([1., 2.])

In [38]:
#numpy.asanyarray - it will convert only if data is not in form of array
a = [1,2]
np.asanyarray(a)

array([1, 2])

In [40]:
a = np.matrix([[1,3],[4,5]])
a

matrix([[1, 3],
        [4, 5]])

In [41]:
a = np.matrix([1,2])

In [42]:
np.asanyarray(a) #it will not convert to array because matrix is subset of array and it's already in form of array

matrix([[1, 2]])

In [43]:
# Copy
# 1. deep copy
# 2. shalow copy

In [44]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [45]:
# deep copy
y = x

In [46]:
# if i change some value of y , the x value will get changed
y[2] = 5

In [47]:
y

array([1, 2, 5, 4])

In [48]:
x

array([1, 2, 5, 4])

In [49]:
# Shalow copy - if i change value of y it will not effect x
y = np.copy(x)

In [50]:
y[3] = 10

In [51]:
y

array([ 1,  2,  5, 10])

In [52]:
x

array([1, 2, 5, 4])

In [54]:
# Numpy.fromfunction - used for generating array or matrix
# np.fromfunction(function, dimension, dtype)
np.fromfunction(lambda i, j: i == j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [55]:
# np.fromfunction(lambda i, j: i*j, (3,3,3), dtype=int) - (3,3,3) -> 3 dim
np.fromfunction(lambda i, j: i*j, (3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [56]:
np.fromfunction(lambda i, j, k : i*j*k, (3,3, 2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [57]:
# np.fromiter
iter = (x*x for x in range(5))
iter

<generator object <genexpr> at 0x7fa895638350>

In [62]:
np.fromiter(iter, int)

array([ 0,  1,  4,  9, 16])

In [60]:
x = [x*x for x in range(5)]
x

[0, 1, 4, 9, 16]

In [68]:
# np.fromstring
a = np.fromstring('23 45',dtype=int, sep=" ")
a

array([23, 45])

In [69]:
# create record
x1 = np.array([1,2,3,4])
x1

array([1, 2, 3, 4])

In [71]:
x2 = np.array(['aa','bb','cc','dd'])
x2

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [77]:
x3 = np.array([1,2,3,4])
x4 = np.array([1,2,3,4])

In [78]:
type(x4)

numpy.ndarray

In [79]:
rec = np.core.records.fromarrays([x1,x2,x3,x4], names='a,b,c,d')
rec

rec.array([(1, 'a', 1, 1), (2, 'b', 2, 2), (3, 'c', 3, 3), (4, 'd', 4, 4)],
          dtype=[('a', '<i8'), ('b', '<U1'), ('c', '<i8'), ('d', '<i8')])

In [80]:
# Datatype

In [81]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [82]:
type(arr)

numpy.ndarray

In [83]:
arr_mat = [[1,2,3],[2,3,4],[4,5,6]]
arr_mat

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]

In [91]:
mat = np.array(arr_mat)
print("Type: ", type(mat))
print("Matrix: \n", mat)
print("Dimension: ", mat.ndim, sep="")
print("Size: ", mat.size)
print("Shap: ",mat.shape)
print("Data types of mat", mat.dtype)

Type:  <class 'numpy.ndarray'>
Matrix: 
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Dimension: 2
Size:  9
Shap:  (3, 3)
Data types of mat int64


In [92]:
# Arange and linspace

In [96]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [98]:
list(range(0, 50, 2)) #we can't give step as in float ,list(range(0, 50, 2.5)) like 2.5 -> will give error

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [100]:
np.arange(5,20,2.5) #we can give floating point as steps

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [104]:
# Every 5th num from 50 in reverse order
# np.arange(start, end, steps)
np.arange(50, 0, -1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [108]:
# Linespace
# np.linespace(start, end, numberOfData)
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [109]:
# we can exclude last poin
np.linspace(1,10, 5, endpoint=False)

array([1. , 2.8, 4.6, 6.4, 8.2])

In [127]:
np.linspace(2.0,3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [128]:
np.linspace(2.0,3.0,num=5,retstep=True) #will give steps how much it's took

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [110]:
# Matrix creation

In [111]:
# np.zeros()
np.zeros(5) #will generate 5 zeros

array([0., 0., 0., 0., 0.])

In [113]:
np.zeros((3,4)) #0 of 3*4 matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
# np.ones()
np.ones(5)

array([1., 1., 1., 1., 1.])

In [116]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [118]:
# matix dim specified by the tuples
np.zeros((3,4,2)) # 3 -> 4*2

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [119]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [122]:
# np.empty() - will create array with some random num
np.empty((3,5))

array([[ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857],
       [ 4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429],
       [ 7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]])

In [125]:
# Identity matrix -> diagonal of matrix should be 1 and sqar in shap
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [129]:
# Log
np.logspace(2.0,3.0, num=4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [132]:
np.logspace(2.0,3.0, num=4,base=10, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [133]:
np.logspace(2.0,3.0, num=4,base=2)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [139]:
# np.reshape()-> used for reshaping a dataset (dim/shape should always equals to the numbers)
x = np.arange(16).reshape(2,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [140]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [141]:
# get the diagonal element
np.diag(x)

array([ 0,  5, 10, 15])

In [142]:
# np.diag(x, k=2)-> will skip k index and will make squar matrix
np.diag(x, k=0)

array([ 0,  5, 10, 15])

In [143]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [144]:
np.diag(x, k=2)

array([2, 7])

In [145]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [146]:
# if you call diag inside diag(), the matrix will try to reconstruct
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [147]:
# diagflat() - reconstruct diag values
np.diagflat([[1,2],[3,4]])


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [148]:
np.diagflat([[1,2],[3,4]], k =1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [150]:
np.diagflat([1,2])

array([[1, 0],
       [0, 2]])

In [152]:
np.diagflat([1,2], k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [154]:
# triagnal in numpy - will increase num of 1's in trangle form
# np.tri(numRow, numCol, k)
np.tri(3,5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [157]:
np.tri(3,5, dtype=int, k =1)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [161]:
np.tri(3,5,2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [167]:
# return a lower triangle of an array
np.tril([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [168]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], k=1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
# return a upper triangle of an array
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [170]:
np.triu([[1,2,3],[4,5,6],[7,8,9]], k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [172]:
# Random number generation np.rand()-> the data will be inform distribution ->value will be in between 0 to 1
np.random.rand(4)

array([0.99135673, 0.03627571, 0.07242216, 0.00180712])

In [174]:
np.random.rand(4,4) #kind of 2d array

array([[0.89483168, 0.4104732 , 0.87898216, 0.41875367],
       [0.32480734, 0.94238089, 0.9344661 , 0.74762646],
       [0.82832256, 0.95171483, 0.02860124, 0.69357469],
       [0.70830016, 0.91512496, 0.07723841, 0.29027652]])

In [175]:
# randn() - > the data set will have mean = 0 and std = 1
np.random.randn(4,3)

array([[-0.46475446, -0.36375669,  0.21764378],
       [-0.34631074,  0.99306563, -0.89957457],
       [-1.41807143, -0.36460819,  0.69796346],
       [ 0.738082  , -1.29887623, -0.18486626]])

In [176]:
np.random.randn(4,4)

array([[ 0.76357616, -0.19888449,  0.40257194, -0.15093008],
       [-0.4067841 ,  0.0995277 , -1.14140139, -0.14748424],
       [ 0.94832162, -1.1955737 , -1.01792642, -0.46568246],
       [-0.87761686,  0.06365972,  1.36376419,  0.46542451]])

In [177]:
# randint(low, high=None, size=None, dtype='l') ->
np.random.randint(1,100,(4,4))

array([[59, 36, 75, 26],
       [55, 37, 51, 40],
       [52, 71, 61, 31],
       [25, 75, 22, 56]])

In [178]:
# Reshaping
from numpy.random import randint as ri
a = ri(1,100,30)

In [179]:
a

array([96, 88, 28, 64, 35, 24, 58, 64, 25, 21, 37, 14, 17, 73, 57, 83, 91,
       45, 51, 31, 41, 87,  2, 80, 44, 22, 42, 29, 33, 27])

In [181]:
# reshaping
a.reshape(10,3)

array([[96, 88, 28],
       [64, 35, 24],
       [58, 64, 25],
       [21, 37, 14],
       [17, 73, 57],
       [83, 91, 45],
       [51, 31, 41],
       [87,  2, 80],
       [44, 22, 42],
       [29, 33, 27]])

In [182]:
a.reshape(10,-9999)

array([[96, 88, 28],
       [64, 35, 24],
       [58, 64, 25],
       [21, 37, 14],
       [17, 73, 57],
       [83, 91, 45],
       [51, 31, 41],
       [87,  2, 80],
       [44, 22, 42],
       [29, 33, 27]])

In [183]:
a = ri(1,100,25)
a

array([29, 14, 47, 22, 29, 30, 76, 18, 34, 15, 14, 17,  3, 49, 15, 55, 65,
       29, 30, 34, 45, 87, 81, 30, 50])

In [184]:
# sorting - ascending order np.sort(a, axis=-1, kind=None, order=None)
np.sort(a)


array([ 3, 14, 14, 15, 15, 17, 18, 22, 29, 29, 29, 30, 30, 30, 34, 34, 45,
       47, 49, 50, 55, 65, 76, 81, 87])

In [187]:
m = ri(1,100,25).reshape(5,5)
m

array([[ 4, 15, 44, 12, 13],
       [81, 55,  3, 29, 46],
       [60, 64, 48, 92, 22],
       [46, 66, 74, 25, 16],
       [55, 54, 16, 39, 56]])

In [188]:
np.sort(m, axis=1, kind='mergesort') #will sort on rows

array([[ 4, 12, 13, 15, 44],
       [ 3, 29, 46, 55, 81],
       [22, 48, 60, 64, 92],
       [16, 25, 46, 66, 74],
       [16, 39, 54, 55, 56]])

In [189]:
np.sort(m, axis=0, kind='mergesort') #will sort on column

array([[ 4, 15,  3, 12, 13],
       [46, 54, 16, 25, 16],
       [55, 55, 44, 29, 22],
       [60, 64, 48, 39, 46],
       [81, 66, 74, 92, 56]])

In [191]:
# argmax() -> maximum value index
m.argmax(axis=1) #column label

array([2, 0, 3, 2, 4])

In [192]:
m.argmax() #row label

13

In [196]:
# Indexing and slicing
arr = np.arange(1,12)

In [197]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [198]:
# indexing
arr[7]

8

In [199]:
arr[9]

10

In [201]:
# take data from 1 to 8
# arr[start : end : steps]
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [204]:
arr[0:8:2]

array([1, 3, 5, 7])

In [206]:
arr[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [216]:
arr[-1]

11

In [219]:
mat = np.array(ri(1,100,45)).reshape(3,5,3)
mat

array([[[38, 87, 74],
        [48, 32, 94],
        [62, 58, 41],
        [24, 35, 33],
        [15, 52, 15]],

       [[56, 20, 24],
        [65, 10, 63],
        [23, 59, 63],
        [49, 28, 94],
        [89,  2, 81]],

       [[26, 20,  5],
        [29, 23, 88],
        [21, 55, 21],
        [27, 98, 40],
        [30, 45, 67]]])

In [220]:
# slicing opreation
mat[0]

array([[38, 87, 74],
       [48, 32, 94],
       [62, 58, 41],
       [24, 35, 33],
       [15, 52, 15]])

In [221]:
mat[0][1]

array([48, 32, 94])

In [223]:
mat[0][1][0]

48

In [229]:
mat[0][:,1]

array([87, 32, 58, 35, 52])

In [236]:
mat[0:3,:2]

array([[[38, 87, 74],
        [48, 32, 94]],

       [[56, 20, 24],
        [65, 10, 63]],

       [[26, 20,  5],
        [29, 23, 88]]])

In [237]:
# Conditional operation -> subseting
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[57, 32, 88, 16, 29],
       [47, 34, 77, 16, 62],
       [11, 85, 95, 22, 62]])

In [240]:
# filter - value > 15
mat>15

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [239]:
mat[mat>15]

array([57, 32, 88, 16, 29, 47, 34, 77, 16, 62, 85, 95, 22, 62])

In [249]:
# Universal Functions
mat1 = np.array(ri(10,100,15)).reshape(3,5)
mat1

array([[44, 82, 88, 94, 84],
       [36, 13, 83, 59, 47],
       [30, 41, 78, 92, 18]])

In [250]:
# Conditional operation -> subseting
mat2 = np.array(ri(100,110,15)).reshape(3,5)
mat2

array([[100, 108, 105, 109, 100],
       [104, 100, 100, 106, 109],
       [106, 101, 100, 103, 108]])

In [251]:
# multiplication
mat1*mat2

array([[ 4400,  8856,  9240, 10246,  8400],
       [ 3744,  1300,  8300,  6254,  5123],
       [ 3180,  4141,  7800,  9476,  1944]])

In [252]:
# division
mat1/10

array([[4.4, 8.2, 8.8, 9.4, 8.4],
       [3.6, 1.3, 8.3, 5.9, 4.7],
       [3. , 4.1, 7.8, 9.2, 1.8]])

In [254]:
# Brodcasting
start = np.zeros((4,4))
start =start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [255]:
# create a rank 1 ndarray with 3 values
add_rows=np.array([1,0,2,5])
add_rows

array([1, 0, 2, 5])

In [256]:
y = start+add_rows
y

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.]])

In [257]:
# sqar root
np.sqrt(mat1)

array([[6.63324958, 9.05538514, 9.38083152, 9.69535971, 9.16515139],
       [6.        , 3.60555128, 9.11043358, 7.68114575, 6.8556546 ],
       [5.47722558, 6.40312424, 8.83176087, 9.59166305, 4.24264069]])

In [258]:
# exp
np.exp(mat1)

array([[1.28516001e+19, 4.09399696e+35, 1.65163625e+38, 6.66317622e+40,
        3.02507732e+36],
       [4.31123155e+15, 4.42413392e+05, 1.11286375e+36, 4.20121040e+25,
        2.58131289e+20],
       [1.06864746e+13, 6.39843494e+17, 7.49841700e+33, 9.01762841e+39,
        6.56599691e+07]])